# Generated by Django 2.2.24 on 2021-10-28 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='countdown timer'),
            preserve_default=False,
        ),
    ]
